// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFxULJNHxfOf-A5r0xH_7OvnnkdXJGuD0',
    appId: '1:936059417231:web:0052943e50538ba936f6fa',
    messagingSenderId: '936059417231',
    projectId: 'projetoda-1c317',
    authDomain: 'projetoda-1c317.firebaseapp.com',
    storageBucket: 'projetoda-1c317.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIMhMF742S4VVd4Y3o5CcndA6QJnPU_74',
    appId: '1:936059417231:android:c8bb5c8a0b107a5236f6fa',
    messagingSenderId: '936059417231',
    projectId: 'projetoda-1c317',
    storageBucket: 'projetoda-1c317.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu_JFpdOqqltkAp05W2aE9arLNsode7BI',
    appId: '1:936059417231:ios:07571155fb1ffe4f36f6fa',
    messagingSenderId: '936059417231',
    projectId: 'projetoda-1c317',
    storageBucket: 'projetoda-1c317.appspot.com',
    iosBundleId: 'com.example.projetoDa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu_JFpdOqqltkAp05W2aE9arLNsode7BI',
    appId: '1:936059417231:ios:7d6b2a19c911ed9b36f6fa',
    messagingSenderId: '936059417231',
    projectId: 'projetoda-1c317',
    storageBucket: 'projetoda-1c317.appspot.com',
    iosBundleId: 'com.example.projetoDa.RunnerTests',
  );
}
